apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: tugrulhan/form-anket-backend:v2
        ports:
        - containerPort: 8081
        env:
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-cm
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-cm
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-cm
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_PASS
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: JWT_SECRET_KEY
